apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: mlops-api
  labels:
    app: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: puenayan1/mlops-api:v2
          args:
            
          ports:
            - containerPort: 5678
